spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/structura_users_db
    username: postgres
    password: postgres2024
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  management:
    endpoints:
      web:
        exposure:
          include: health, info
